### ISSUE TITLE
pdf: Error on device update! since HA 2022.12.0 update

### ISSUE THREAD

**Issue by bersonsteve** [emcniece/ha_pdf#4]
Sensor setup is failing since Home Assistant release 2022.12.0 with the following error message in the log:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 503, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 729, in async_device_update
    await task
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ha_pdf/sensor.py", line 114, in update
    page = pdf.getPage(int(self._pdf_page))
  File "/usr/local/lib/python3.10/site-packages/PyPDF2/_reader.py", line 476, in getPage
    deprecation_with_replacement(
  File "/usr/local/lib/python3.10/site-packages/PyPDF2/_utils.py", line 369, in deprecation_with_replacement
    deprecation(DEPR_MSG_HAPPENED.format(old_name, removed_in, new_name))
  File "/usr/local/lib/python3.10/site-packages/PyPDF2/_utils.py", line 351, in deprecation
    raise DeprecationError(msg)
PyPDF2.errors.DeprecationError: reader.getPage(pageNumber) is deprecated and was removed in PyPDF2 3.0.0. Use reader.pages[page_number] instead.

```

Updating line 114 to this fixes the issue:
`page = pdf.pages[int(self._pdf_page)]`

**Comment by emcniece** [comment]
Pushed to `master` branch: https://github.com/emcniece/ha_pdf/commit/253ad7e21986d2db735bd6d78c5037f9c4f7d671

Thanks for the report and the solution!
